name: CI

on:
  push:
  pull_request:

jobs:
  code-validation:
    name: Code validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install typos
        run: cargo install typos-cli

      - name: Check formatting
        run: make formatter-check

      - name: Check linting
        run: make linter-check

      - name: Check spelling
        run: make spellchecker-check

  tests:
    name: Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: macos-latest
          - os: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Run tests
        run: make tests-run
